### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by jayplattuk** [seansay/atom-tidal#12]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [tidal](https://github.com/seansay/atom-tidal) package, v0.6.6

### Stack Trace

Uncaught Error: spawn EACCES

```
At child_process.js:1160

Error: spawn EACCES
    at exports._errnoException (util.js:753:11)
    at ChildProcess.spawn (child_process.js:1160:11)
    at exports.spawn (child_process.js:993:9)
    at REPL.module.exports.REPL.doSpawn (/Users/jay/.atom/packages/tidal/lib/repl.coffee:58:19)
    at REPL.module.exports.REPL.start (/Users/jay/.atom/packages/tidal/lib/repl.coffee:113:12)
    at atom-workspace.REPL.atom.commands.add.tidal:boot (/Users/jay/.atom/packages/tidal/lib/repl.coffee:33:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:246:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:159:19)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:75:30)
```

### Commands

```
     -0:16.4 core:save (atom-text-editor.editor.is-focused)
     -0:00.8 tidal:boot (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "tidal": {
    "ghciPath": "/usr/bin/"
  }
}
```

### Installed Packages

```coffee
# User
tidal, v0.6.6

# Dev
No dev packages
```

**Comment by jayplattuk** [comment]
This is completely new to me - could do with a hand getting started...

**Comment by seansay** [comment]
search in stackoverflow get this http://stackoverflow.com/a/19026627, may is your `ghci` file's permission problem.

can you run ` sudo chmod -R a+rwx  /path/to/yout/ghci`, the default ghci shoud be `/usr/local/bin/ghci`

**Comment by jayplattuk** [comment]
Hi, I ran that and got "No such file or directory"...

**Comment by seansay** [comment]
I believe thats not your ghci path I think, what's the result when you run `which ghci`?

**Comment by jayplattuk** [comment]
Rebooted laptop twice (??) and it somehow fixed itself! Thanks for the help anyway!

**Comment by seansay** [comment]
@jayplattuk 
weird! so I'll close this issue now, you can open a new issue if you have any other problem :)
