### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by kqvc** [seansay/atom-tidal#16]
[Enter steps to reproduce below:]

1. Packages --> Tidal -- > Boot Tidal

**Atom Version**: 0.196.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.9.5
**Thrown From**: [tidal](https://github.com/seansay/atom-tidal) package, v0.6.6

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/kqvc/.atom/packages/tidal/lib/repl.coffee:67

TypeError: undefined is not a function
  at REPL.module.exports.REPL.getEditor (/Users/kqvc/.atom/packages/tidal/lib/repl.coffee:67:20)
  at REPL.module.exports.REPL.editorIsTidal (/Users/kqvc/.atom/packages/tidal/lib/repl.coffee:29:14)
  at atom-workspace.REPL.atom.commands.add.tidal:boot (/Users/kqvc/.atom/packages/tidal/lib/repl.coffee:22:24)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:71:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -4:06.9.0 tidal:boot (atom-text-editor.editor)
     -2:29.9.0 core:copy (atom-text-editor#tidal.ghciPath.editor.mini)
  3x -0:45.2.0 tidal:boot (atom-text-editor#tidal.ghciPath.editor.mini)
```

### Config

```json
{
  "core": {},
  "tidal": {
    "ghciPath": "/usr/bin/ghci"
  }
}
```

### Installed Packages

```coffee
# User
tidal, v0.6.6

# Dev
No dev packages
```

**Comment by seansay** [comment]
where is  your `ghci` path, can you run `which ghci` to confirm ?
if you're using `homebrew` to install haskell and cabal, maybe tha path is `/usr/local/bin/ghci` instead of `/usr/bin/ghci`

**Comment by kqvc** [comment]
Hi there, circling back on this because i'm still having the same problem. Thanks for your help.

which ghci in terminal returns: /usr/bin/ghci/

i've identified this path in the Tidal package settings in Atom.  I had originally installed Haskell via the binary download here - https://www.haskell.org/platform/mac.html 

Today I tried installing via terminal with brew install ghc cabal-install

Same error occurs as above.  Do you think this problem is occurring because the Tidal package can't find Haskell?

**Comment by seansay** [comment]
maybe you can uninstall the old haskell (and related thing), and do a refresh install from the [guide](http://tidal.lurk.org/getting_started.html#tidal-on-mac-os-x)

**Comment by seansay** [comment]
@kqvc 
Hi, so you solve this already?

**Comment by seansay** [comment]
close
