### ISSUE TITLE
Handle things a bit better when cursor not on code

### ISSUE THREAD

**Issue by yaxu** [seansay/atom-tidal#2]
If I rest my cursor above some code and do option-enter, the console pops up and I get this:
  Uncaught TypeError: Cannot read property 'start' of undefined /usr/share/atom/resources/app/node_modules/text-buffer/lib/range.js:26

Mind you it's handy to have the console open to see error messages..

**Comment by yaxu** [comment]
Ah tried with latest atom and it doesn't open a console, but does pop up the same error:
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: linux 3.13.0-37-generic
**Thrown From**: [tidal](https://github.com/seansay/atom-tidal) package, v0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'start' of undefined

```
At /usr/share/atom/resources/app/node_modules/text-buffer/lib/range.js:26

TypeError: Cannot read property 'start' of undefined
  at Function.module.exports.Range.fromObject (/usr/share/atom/resources/app/node_modules/text-buffer/lib/range.js:26:31)
  at TextBuffer.module.exports.TextBuffer.getTextInRange (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:351:36)
  at TextEditor.module.exports.TextEditor.getTextInBufferRange (/usr/share/atom/resources/app/src/text-editor.js:641:26)
  at REPL.module.exports.REPL.getMultiLineExpression (/home/alex/.atom/packages/tidal/lib/repl.coffee:117:25)
  at REPL.module.exports.REPL.currentExpression (/home/alex/.atom/packages/tidal/lib/repl.coffee:101:37)
  at REPL.module.exports.REPL.eval (/home/alex/.atom/packages/tidal/lib/repl.coffee:57:28)
  at atom-text-editor.REPL.atom.commands.add.tidal:eval-multi-line (/home/alex/.atom/packages/tidal/lib/repl.coffee:20:35)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -0:00.7 tidal:eval-multi-line (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "graphite-ui",
      "adventurous-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
adventurous-syntax, v0.1.2
autocomplete-plus, v2.0.3
graphite-ui, v0.13.2
ide-haskell, v0.3.0
language-haskell, v1.0.0
linter-hlint, v0.3.1
tidal, v0.3.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by yaxu** [comment]
BTW there are a lot of deprecation warnings with that atom too..

**Comment by seansay** [comment]
I apologize for the delay, kind of busy these day……now it's chinese new year holiday finally had time to look at this.

Just publish 0.3.1 to fix eval empty line

` deprecation warnings ` seems to come from the upgrading to 1.0 movement, https://atom.io/docs/v0.179.0/upgrading/upgrading-your-package. I take try move the deprecated api first.

**Comment by seansay** [comment]
Just update to `0.4.0`! all deprecated waring should be gone. 

try to working on display ghci ouput to editor

**Comment by yaxu** [comment]
Nice work, thanks a lot!

I noticed that with multiline evals, some characters aren't counted, for example the trailing square bracket here isn't included, and the pattern doesn't evaluate:

```
d1 $ weave 16 (speed (scale 1 1.4 sine1)) [jux (iter 8) $ sound "sd8:4*4",
                                           jux (iter 4) $ sound "bd*2",
                                           jux (iter 3) $ sound "sd8:3*4"
                                          ]
```

**Comment by yaxu** [comment]
Oh and happy new year :)

**Comment by seansay** [comment]
@yaxu 
Thx! not sure why the trailing `]` doesn't get evaluated, need to check that!

**Comment by yaxu** [comment]
Thanks @seansay ! It happens also e.g. if `,` is on its own line.. I guess something is looking for letters of the alphabet.
