### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by euwbah** [seansay/atom-tidal#22]
[Enter steps to reproduce below:]

1. Boot Tidal

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Home
**Thrown From**: [tidal](https://github.com/seansay/atom-tidal) package, v2.1.0

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:141

Error: write EPIPE
  at exports._errnoException (util.js:814:11)
  at Socket._writeGeneric (net.js:672:26)
  at Socket._write (net.js:691:8)
  at doWrite (_stream_writable.js:291:12)
  at writeOrBuffer (_stream_writable.js:277:5)
  at Socket.Writable.write (_stream_writable.js:206:11)
  at Socket.write (net.js:615:40)
  at REPL.module.exports.REPL.stdinWrite (C:\Users\Matthew_Tan\.atom\packages\tidal\lib\repl.coffee:56:17)
  at REPL.module.exports.REPL.tidalSendLine (C:\Users\Matthew_Tan\.atom\packages\tidal\lib\repl.coffee:59:6)
  at REPL.module.exports.REPL.initTidal (C:\Users\Matthew_Tan\.atom\packages\tidal\lib\repl.coffee:53:7)
  at REPL.module.exports.REPL.start (C:\Users\Matthew_Tan\.atom\packages\tidal\lib\repl.coffee:70:6)
  at atom-workspace.REPL.atom.commands.add.tidal:boot (C:\Users\Matthew_Tan\.atom\packages\tidal\lib\repl.coffee:23:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Matthew_Tan\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (C:\Users\Matthew_Tan\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Matthew_Tan\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:145:19)
  at EventEmitter.<anonymous> (C:\Users\Matthew_Tan\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
     -0:17.5.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:03.1.0 tidal:boot (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "tidal": {
    "ghciPath": "C:\\Program Files\\Haskell Platform\\7.10.2-a\\bin"
  }
}
```

### Installed Packages

```coffee
# User
tidal, v2.1.0

# Dev
No dev packages
```

**Comment by euwbah** [comment]
Never mind, I realised I left out "/ghci.exe" at the end of the path in ghci path settings.

**Comment by seansay** [comment]
:clap:
