### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stdin' of undefined

### ISSUE THREAD

**Issue by yaxu** [seansay/atom-tidal#4]
The plugin crashes if you try to evaluate something without first booting tidal.

To reproduce:
1. Open a tidal file
2. Try to evaluate something without booting tidal first..

Maybe a little error should pop up, or maybe it should  just boot tidal if it's not already running?

**Atom Version**: 0.176.0
**System**: linux 3.13.0-37-generic
**Thrown From**: [tidal](https://github.com/seansay/atom-tidal) package, v0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'stdin' of undefined

```
At /home/alex/.atom/packages/tidal/lib/repl.coffee:38

TypeError: Cannot read property 'stdin' of undefined
  at REPL.module.exports.REPL.stdinWrite (/home/alex/.atom/packages/tidal/lib/repl.coffee:38:10)
  at REPL.module.exports.REPL.tidalSendLine (/home/alex/.atom/packages/tidal/lib/repl.coffee:41:6)
  at REPL.module.exports.REPL.tidalSendExpression (/home/alex/.atom/packages/tidal/lib/repl.coffee:45:6)
  at /home/alex/.atom/packages/tidal/lib/repl.coffee:82:8
  at REPL.module.exports.REPL.evalWithRepl (/home/alex/.atom/packages/tidal/lib/repl.coffee:84:5)
  at REPL.module.exports.REPL.eval (/home/alex/.atom/packages/tidal/lib/repl.coffee:59:6)
  at atom-text-editor.REPL.atom.commands.add.tidal:eval-multi-line (/home/alex/.atom/packages/tidal/lib/repl.coffee:21:35)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
  2x -0:01.8 core:move-up (atom-text-editor.editor.is-focused)
     -0:01.2 tidal:eval-multi-line (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "graphite-ui",
      "adventurous-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
adventurous-syntax, v0.1.2
autocomplete-plus, v2.0.3
graphite-ui, v0.13.2
ide-haskell, v0.3.0
language-haskell, v1.0.0
linter-hlint, v0.3.1
tidal, v0.4.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by seansay** [comment]
thx, got that!

**Comment by seansay** [comment]
now I just don't eval if the repl is not start, need more time to work to make the console output to the editor

**Comment by yaxu** [comment]
Thanks @seansay 

Just wondering about doing this instead:

I.e. just start tidal if it's not running. This works ok for me, and is maybe nice for beginners.

```
  stdinWrite: (command) ->
    if not @repl?
      @start()
    @repl.stdin.write(command)
```

**Comment by seansay** [comment]
@yaxu 
I'm thinking about an alert window saying that `you need boot tidal first`, and two button `cancel` and `boot`. It's this better?

**Comment by yaxu** [comment]
Yes that would be good

**Comment by seansay** [comment]
updated! @yaxu

**Comment by yaxu** [comment]
Thanks a lot @seansay, I still prefer it if it just boots on the first eval, maybe it could be an option? Closing this for now though
